Ejercicio_MVC/Ejercicio_MVC2/Models/ErrorViewModel.cs
namespace Ejercicio_MVC2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Ejercicio_MVC/Ejercicio_MVC2/Models/Persona.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Ejercicio_MVC2.Models
{
    public class Person
    {
        public Person(int id, string name, int age, string? email)
        {
            this.Id = id;
            this.Name = name;
            this.Age = age;
            this.Email = email;
        }
        public int Id { get; set; }

        [DisplayName("Nombre")]
        public string Name { get; set; }

        [DisplayName("Edad")]
        public int Age { get; set; }

        [EmailAddress]
        public string? Email { get; set; }
    }
}

Ejercicio_MVC/Ejercicio_MVC2/Controllers/HomeController.cs
using Ejercicio_MVC2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Ejercicio_MVC2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Ejercicio_MVC/Ejercicio_MVC2/Controllers/SaludosController.cs
using Ejercicio_MVC2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

namespace Ejercicio_MVC2.Controllers
{
    public class SaludosController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Despedida()
        {
            return View();
        }

        public IActionResult Felicita(int ID, string name, int age)
        {
            ViewBag.Id = ID;
            ViewBag.Name = name;
            ViewBag.Age = age;
            return View();
        }

        public IActionResult Perfil(int ID, string Name, int Age)
        {
            Person person = new Person(ID, Name, Age, Name.ToLower()+"dominio.es");

            return View(person);
        }
    }
}

Ejercicio_MVC/Ejercicio_MVC2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Ejercicio_MVC/Ejercicio_MVC2/Views/Saludos/Despedida.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Página Despedida";
}

<h2> Despedida Action - Saludos Controller</h2>

<p>¡Adiós a todo el mundo!</p>

Ejercicio_MVC/Ejercicio_MVC2/Views/Saludos/Felicita.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Página Despedida";
}

<h1>Hoy el usuario con ID: @ViewBag.Id cumple @ViewBag.Age años</h1>
<ul>
    @for (int i = 0; i < ViewBag.Age; i++)
    {
        <li><a asp-controller="Saludos" asp-action="Index">Felicidades @ViewBag.Name</a></li>
    }
</ul>

Ejercicio_MVC/Ejercicio_MVC2/Views/Saludos/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Página Saludos";
}

<h2> Index Action - Saludos Controller</h2>

<p>¡Hola a todo el mundo!</p>

Ejercicio_MVC/Ejercicio_MVC2/Views/Saludos/Perfil.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model Ejercicio_MVC2.Models.Person;
    ViewData["Title"] = "Página Perfil";
}
<h1>Usuario: @Html.DisplayFor(model => model.Id)</h1>
<ul>
    <li>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</li>
    <li>@Html.DisplayNameFor(model => model.Age): @Html.DisplayFor(model => model.Age)</li>
    <li>@Html.DisplayNameFor(model => model.Email): @Html.DisplayFor(model => model.Email)</li>
</ul>

Ejercicio_MVC/Ejercicio_MVC2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ejercicio_MVC2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ejercicio_MVC2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ejercicio_MVC2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Saludos" asp-action="Index">Saluda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Saludos" asp-action="Despedida">Despide</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Ejercicio_MVC2 - Proyecto de Arturo
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>